-- Create Tools Table
create table tools (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  status text not null default 'up', -- 'up', 'down', 'service'
  location text,
  license_req boolean default true,
  description text
);

-- Insert Initial Tools
insert into tools (name, category, status, location, license_req, description) values
('Raith EBPG 5200', 'Lithography', 'up', 'Cleanroom D', true, 'Electron Beam Lithography system. High resolution patterning.'),
('Heidelberg DWL 2000', 'Lithography', 'up', 'Cleanroom D', true, 'Laser lithography system for mask making and direct write.'),
('JEOL 7800F Prime', 'Metrology', 'up', 'Analysis Lab', true, 'High resolution SEM with EDS.'),
('Dektak XT', 'Metrology', 'up', 'Cleanroom E', false, 'Stylus profilometer.'),
('Oxford PlasmaPro 100', 'Etching', 'down', 'Cleanroom A', true, 'ICP-RIE for III-V etching. Currently undergoing maintenance.'),
('Lesker PVD 225', 'Deposition', 'service', 'Cleanroom B', true, 'E-beam evaporator for metals.'),
('Disco DAD 3350', 'Processing', 'up', 'Back-end Lab', true, 'Dicing saw.');

-- Create Bookings Table
create table bookings (
  id bigint generated by default as identity primary key,
  tool_id bigint references tools(id),
  tool_name text, -- Denormalized for easier display
  user_id uuid references auth.users(id),
  user_name text,
  project text,
  date text not null, -- YYYY-MM-DD
  time text not null, -- HH:MM
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
);

-- Enable RLS for Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, first_name, last_name, job_title, access_level, licenses)
  values (
    new.id,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'job_title',
    coalesce(new.raw_user_meta_data->>'access_level', 'user'),
    '[]'::jsonb
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
