-- ==============================================================================
-- 20231201000000_initial_schema.sql
-- Initial Schema for MMI-LIMS (Tools, Profiles, Bookings)
-- ==============================================================================

-- 1. Tools Table
CREATE TABLE IF NOT EXISTS public.tools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'up' CHECK (status IN ('up', 'down', 'service')),
  location text,
  license_req boolean NOT NULL DEFAULT true,
  description text
);

-- Seed Initial Tools if table is empty
INSERT INTO public.tools (name, category, status, location, license_req, description)
SELECT name, category, status, location, license_req, description FROM (
  VALUES
    ('Raith EBPG 5200', 'Lithography', 'up', 'Cleanroom D', true, 'Electron Beam Lithography system. High resolution patterning.'),
    ('Heidelberg DWL 2000', 'Lithography', 'up', 'Cleanroom D', true, 'Laser lithography system for mask making and direct write.'),
    ('JEOL 7800F Prime', 'Metrology', 'up', 'Analysis Lab', true, 'High resolution SEM with EDS.'),
    ('Dektak XT', 'Metrology', 'up', 'Cleanroom E', false, 'Stylus profilometer.'),
    ('Oxford PlasmaPro 100', 'Etching', 'down', 'Cleanroom A', true, 'ICP-RIE for III-V etching. Currently undergoing maintenance.'),
    ('Lesker PVD 225', 'Deposition', 'service', 'Cleanroom B', true, 'E-beam evaporator for metals.'),
    ('Disco DAD 3350', 'Processing', 'up', 'Back-end Lab', true, 'Dicing saw.')
) AS v(name, category, status, location, license_req, description)
WHERE NOT EXISTS (SELECT 1 FROM public.tools);

-- 2. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name text,
  last_name text,
  access_level text NOT NULL DEFAULT 'user' CHECK (access_level IN ('user', 'admin')),
  is_approved boolean NOT NULL DEFAULT false,
  licenses jsonb NOT NULL DEFAULT '[]'::jsonb,
  projects text[] NOT NULL DEFAULT '{}'::text[],
  updated_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- 3. Bookings Table (Initial legacy structure)
CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id bigint NOT NULL REFERENCES public.tools(id) ON DELETE CASCADE,
  tool_name text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name text NOT NULL,
  project text NOT NULL DEFAULT 'General',
  date date NOT NULL,
  time time NOT NULL,
  end_time time,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);
