-- ==============================================================================
-- 20260927000000_baseline_schema.sql
-- MMI-LIMS Complete Baseline Schema with Security, Constraints & RLS
-- ==============================================================================

-- 1. Required Extensions
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Tools Table
CREATE TABLE IF NOT EXISTS public.tools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'up' CHECK (status IN ('up', 'down', 'service')),
  location text,
  license_req boolean NOT NULL DEFAULT true,
  description text
);

-- Insert Default Tools if empty
INSERT INTO public.tools (name, category, status, location, license_req, description)
SELECT name, category, status, location, license_req, description FROM (
  VALUES
    ('Raith EBPG 5200', 'Lithography', 'up', 'Cleanroom D', true, 'Electron Beam Lithography system. High resolution patterning.'),
    ('Heidelberg DWL 2000', 'Lithography', 'up', 'Cleanroom D', true, 'Laser lithography system for mask making and direct write.'),
    ('JEOL 7800F Prime', 'Metrology', 'up', 'Analysis Lab', true, 'High resolution SEM with EDS.'),
    ('Dektak XT', 'Metrology', 'up', 'Cleanroom E', false, 'Stylus profilometer.'),
    ('Oxford PlasmaPro 100', 'Etching', 'down', 'Cleanroom A', true, 'ICP-RIE for III-V etching. Currently undergoing maintenance.'),
    ('Lesker PVD 225', 'Deposition', 'service', 'Cleanroom B', true, 'E-beam evaporator for metals.'),
    ('Disco DAD 3350', 'Processing', 'up', 'Back-end Lab', true, 'Dicing saw.')
) AS v(name, category, status, location, license_req, description)
WHERE NOT EXISTS (SELECT 1 FROM public.tools);

-- 3. Profiles Table (Authorization Data Protected, Bearer Token Removed)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name text,
  last_name text,
  job_title text,
  access_level text NOT NULL DEFAULT 'user' CHECK (access_level IN ('user', 'admin')),
  is_approved boolean NOT NULL DEFAULT false,
  licenses jsonb NOT NULL DEFAULT '[]'::jsonb,
  projects text[] NOT NULL DEFAULT '{}'::text[],
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_profiles_approved ON public.profiles(is_approved);
CREATE INDEX IF NOT EXISTS idx_profiles_access ON public.profiles(access_level);

-- 4. Dedicated Private Calendar Bearer Token Table
-- Calendar tokens are stored as SHA-256 hashes and isolated from user directory queries
CREATE TABLE IF NOT EXISTS public.user_calendar_tokens (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_calendar_tokens_hash ON public.user_calendar_tokens(token_hash);

-- 5. Bookings Table with Interval Range and Exclusion Constraint
CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id bigint NOT NULL REFERENCES public.tools(id) ON DELETE CASCADE,
  tool_name text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name text NOT NULL,
  project text NOT NULL,
  date date NOT NULL,
  time time NOT NULL,
  end_time time NOT NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT booking_time_order CHECK (end_time > time),
  CONSTRAINT booking_starts_ends_order CHECK (ends_at > starts_at),
  CONSTRAINT no_double_booking EXCLUDE USING gist (
    tool_id WITH =,
    tstzrange(starts_at, ends_at, '[)') WITH &&
  )
);

CREATE INDEX IF NOT EXISTS idx_bookings_tool_date ON public.bookings(tool_id, date);
CREATE INDEX IF NOT EXISTS idx_bookings_user_date ON public.bookings(user_id, date);
CREATE INDEX IF NOT EXISTS idx_bookings_starts_at ON public.bookings(starts_at);
CREATE INDEX IF NOT EXISTS idx_bookings_range ON public.bookings USING gist (tstzrange(starts_at, ends_at, '[)'));

-- 6. Non-recursive Admin Check Helper Function
CREATE OR REPLACE FUNCTION public.is_admin(p_user_id uuid)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = p_user_id AND access_level = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Revoke public execution, allow authenticated
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;

-- 7. Safe Profile Update Validation Trigger
-- Disallow non-admins from changing privileged columns (access_level, is_approved, licenses, projects)
CREATE OR REPLACE FUNCTION public.enforce_profile_update_rules()
RETURNS trigger AS $$
BEGIN
  -- If caller is admin, allow all modifications
  IF public.is_admin(auth.uid()) THEN
    NEW.updated_at := timezone('utc'::text, now());
    RETURN NEW;
  END IF;

  -- Ordinary users cannot elevate or modify access_level, is_approved, licenses, or projects
  IF NEW.access_level IS DISTINCT FROM OLD.access_level THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify access_level';
  END IF;
  IF NEW.is_approved IS DISTINCT FROM OLD.is_approved THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify is_approved';
  END IF;
  IF NEW.licenses IS DISTINCT FROM OLD.licenses THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify licenses';
  END IF;
  IF NEW.projects IS DISTINCT FROM OLD.projects THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify projects';
  END IF;

  NEW.updated_at := timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS trg_enforce_profile_update_rules ON public.profiles;
CREATE TRIGGER trg_enforce_profile_update_rules
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_profile_update_rules();

-- 8. Safe Signup Trigger (Hardcode Default Role & Pending Approval)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (
    id,
    first_name,
    last_name,
    job_title,
    access_level,
    is_approved,
    licenses,
    projects
  )
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'job_title', 'Researcher'),
    'user', -- Hardcoded ordinary role
    false,  -- Hardcoded pending approval
    '[]'::jsonb,
    '{}'::text[]
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- 9. Authoritative Booking Validation and Timestamp Assignment Trigger
CREATE OR REPLACE FUNCTION public.validate_and_set_booking_range()
RETURNS trigger AS $$
DECLARE
  v_user_profile public.profiles%ROWTYPE;
  v_tool public.tools%ROWTYPE;
  v_is_admin boolean;
  v_lab_timezone text := 'Europe/Vilnius';
BEGIN
  -- Determine admin status
  v_is_admin := public.is_admin(COALESCE(auth.uid(), NEW.user_id));

  -- Fetch user profile
  SELECT * INTO v_user_profile FROM public.profiles WHERE id = NEW.user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking user profile not found';
  END IF;

  -- Fetch tool
  SELECT * INTO v_tool FROM public.tools WHERE id = NEW.tool_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tool not found';
  END IF;

  -- Derive trusted names from canonical records
  NEW.user_name := TRIM(COALESCE(v_user_profile.first_name, '') || ' ' || COALESCE(v_user_profile.last_name, ''));
  IF NEW.user_name = '' THEN
    NEW.user_name := 'User ' || SUBSTRING(NEW.user_id::text, 1, 8);
  END IF;
  NEW.tool_name := v_tool.name;

  -- Default end_time if omitted
  IF NEW.end_time IS NULL THEN
    NEW.end_time := (NEW.time + interval '30 minutes')::time;
  END IF;

  IF NEW.end_time <= NEW.time THEN
    RAISE EXCEPTION 'end_time (%) must be after time (%)', NEW.end_time, NEW.time;
  END IF;

  -- Compute timezone-aware timestamps (Europe/Vilnius)
  NEW.starts_at := (NEW.date::text || ' ' || NEW.time::text)::timestamp AT TIME ZONE v_lab_timezone;
  NEW.ends_at := (NEW.date::text || ' ' || NEW.end_time::text)::timestamp AT TIME ZONE v_lab_timezone;

  -- Business rules for non-admin callers
  IF NOT v_is_admin THEN
    -- Must act as self
    IF auth.uid() IS NOT NULL AND NEW.user_id <> auth.uid() THEN
      RAISE EXCEPTION 'Unauthorized: cannot create or modify bookings for another user';
    END IF;

    -- Must be approved
    IF NOT v_user_profile.is_approved THEN
      RAISE EXCEPTION 'User account is pending administrator approval';
    END IF;

    -- Tool must be operational
    IF v_tool.status <> 'up' THEN
      RAISE EXCEPTION 'Tool is currently unavailable (status: %)', v_tool.status;
    END IF;

    -- License check
    IF v_tool.license_req THEN
      IF NOT (v_user_profile.licenses @> to_jsonb(v_tool.id)) THEN
        RAISE EXCEPTION 'License required for tool %', v_tool.name;
      END IF;
    END IF;

    -- Cannot book in the past
    IF NEW.ends_at < timezone('utc'::text, now()) THEN
      RAISE EXCEPTION 'Cannot create or modify past bookings';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS trg_validate_and_set_booking_range ON public.bookings;
CREATE TRIGGER trg_validate_and_set_booking_range
  BEFORE INSERT OR UPDATE ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_and_set_booking_range();

-- 10. Atomic Group Booking Update RPC (Eliminates race condition & data loss in L1)
CREATE OR REPLACE FUNCTION public.update_booking_group(
  p_old_ids bigint[],
  p_date date,
  p_start_time time,
  p_end_time time,
  p_project text
)
RETURNS public.bookings AS $$
DECLARE
  v_primary_id bigint;
  v_updated_booking public.bookings%ROWTYPE;
  v_first_booking public.bookings%ROWTYPE;
  v_is_admin boolean;
BEGIN
  IF p_old_ids IS NULL OR array_length(p_old_ids, 1) = 0 THEN
    RAISE EXCEPTION 'No booking IDs provided for update';
  END IF;

  v_primary_id := p_old_ids[1];
  v_is_admin := public.is_admin(auth.uid());

  -- Lock all target rows to prevent concurrent mutation
  SELECT * INTO v_first_booking FROM public.bookings
  WHERE id = v_primary_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found: %', v_primary_id;
  END IF;

  -- Authorization check
  IF NOT v_is_admin AND v_first_booking.user_id <> auth.uid() THEN
    RAISE EXCEPTION 'Unauthorized: not owner of booking %', v_primary_id;
  END IF;

  -- If multiple legacy IDs were grouped, delete the secondary rows first
  IF array_length(p_old_ids, 1) > 1 THEN
    DELETE FROM public.bookings
    WHERE id = ANY(p_old_ids[2:array_length(p_old_ids, 1)]);
  END IF;

  -- Update primary booking (triggers will recalculate range and enforce constraints)
  UPDATE public.bookings
  SET
    date = p_date,
    time = p_start_time,
    end_time = p_end_time,
    project = p_project
  WHERE id = v_primary_id
  RETURNING * INTO v_updated_booking;

  RETURN v_updated_booking;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.update_booking_group(bigint[], date, time, time, text) FROM public;
GRANT EXECUTE ON FUNCTION public.update_booking_group(bigint[], date, time, time, text) TO authenticated;

-- 11. Calendar Token Management RPCs
CREATE OR REPLACE FUNCTION public.rotate_calendar_token(p_token_hash text)
RETURNS boolean AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;
  IF p_token_hash IS NULL OR length(p_token_hash) < 32 THEN
    RAISE EXCEPTION 'Invalid token hash';
  END IF;

  INSERT INTO public.user_calendar_tokens (user_id, token_hash, created_at)
  VALUES (auth.uid(), p_token_hash, timezone('utc'::text, now()))
  ON CONFLICT (user_id) DO UPDATE
  SET
    token_hash = EXCLUDED.token_hash,
    created_at = timezone('utc'::text, now());

  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.rotate_calendar_token(text) FROM public;
GRANT EXECUTE ON FUNCTION public.rotate_calendar_token(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.revoke_calendar_token()
RETURNS boolean AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  DELETE FROM public.user_calendar_tokens WHERE user_id = auth.uid();
  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.revoke_calendar_token() FROM public;
GRANT EXECUTE ON FUNCTION public.revoke_calendar_token() TO authenticated;

-- Check whether the current user has a calendar token configured
CREATE OR REPLACE FUNCTION public.has_calendar_token()
RETURNS boolean AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN false;
  END IF;
  RETURN EXISTS (
    SELECT 1 FROM public.user_calendar_tokens WHERE user_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.has_calendar_token() FROM public;
GRANT EXECUTE ON FUNCTION public.has_calendar_token() TO authenticated;

-- 12. Row Level Security Policies

-- Enable RLS on all tables
ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_calendar_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- TOOLS Policies
DROP POLICY IF EXISTS "Tools viewable by authenticated users" ON public.tools;
DROP POLICY IF EXISTS "Tools are viewable by everyone" ON public.tools;
CREATE POLICY "Tools viewable by authenticated users" ON public.tools
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can update tools" ON public.tools;
CREATE POLICY "Admins can update tools" ON public.tools
  FOR UPDATE USING (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can insert tools" ON public.tools;
CREATE POLICY "Admins can insert tools" ON public.tools
  FOR INSERT WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can delete tools" ON public.tools;
CREATE POLICY "Admins can delete tools" ON public.tools
  FOR DELETE USING (public.is_admin(auth.uid()));

-- PROFILES Policies
-- Only authenticated users can read profiles (no anonymous reads of user directory)
DROP POLICY IF EXISTS "Profiles viewable by authenticated users" ON public.profiles;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Profiles viewable by authenticated users" ON public.profiles
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT WITH CHECK (
    auth.uid() = id AND
    access_level = 'user' AND
    is_approved = false AND
    licenses = '[]'::jsonb AND
    projects = '{}'::text[]
  );

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (
    auth.uid() = id OR public.is_admin(auth.uid())
  );

-- USER CALENDAR TOKENS Policies
-- Only the token owner can access their token row
DROP POLICY IF EXISTS "Calendar token access restricted to owner" ON public.user_calendar_tokens;
CREATE POLICY "Calendar token access restricted to owner" ON public.user_calendar_tokens
  FOR ALL USING (auth.uid() = user_id);

-- BOOKINGS Policies
-- Authenticated users can view bookings (availability/calendar)
DROP POLICY IF EXISTS "Bookings viewable by authenticated users" ON public.bookings;
DROP POLICY IF EXISTS "Bookings are viewable by everyone" ON public.bookings;
CREATE POLICY "Bookings viewable by authenticated users" ON public.bookings
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can insert bookings" ON public.bookings;
DROP POLICY IF EXISTS "Users can create bookings" ON public.bookings;
CREATE POLICY "Users can insert bookings" ON public.bookings
  FOR INSERT WITH CHECK (
    auth.uid() = user_id OR public.is_admin(auth.uid())
  );

DROP POLICY IF EXISTS "Users can update own bookings" ON public.bookings;
CREATE POLICY "Users can update own bookings" ON public.bookings
  FOR UPDATE USING (
    auth.uid() = user_id OR public.is_admin(auth.uid())
  );

DROP POLICY IF EXISTS "Users can delete own bookings" ON public.bookings;
CREATE POLICY "Users can delete own bookings" ON public.bookings
  FOR DELETE USING (
    auth.uid() = user_id OR public.is_admin(auth.uid())
  );
