-- ==============================================================================
-- 20260927000001_security_and_constraints.sql
-- MMI-LIMS Security Hardening, Constraints, RLS, and Business Rules
-- Covers: R1, R2, R3, R4, R7, R8, R13
-- ==============================================================================

-- 1. Required Extensions
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Ensure base tables exist
CREATE TABLE IF NOT EXISTS public.tools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'up' CHECK (status IN ('up', 'down', 'service')),
  location text,
  license_req boolean NOT NULL DEFAULT true,
  description text
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name text,
  last_name text,
  access_level text NOT NULL DEFAULT 'user' CHECK (access_level IN ('user', 'admin')),
  is_approved boolean NOT NULL DEFAULT false,
  licenses jsonb NOT NULL DEFAULT '[]'::jsonb,
  projects text[] NOT NULL DEFAULT '{}'::text[],
  updated_at timestamptz DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id bigint NOT NULL REFERENCES public.tools(id) ON DELETE CASCADE,
  tool_name text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name text NOT NULL,
  project text NOT NULL DEFAULT 'General',
  date date NOT NULL,
  time time NOT NULL,
  end_time time,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Upgrade public.profiles columns (Fixes R3)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN updated_at timestamptz DEFAULT timezone('utc'::text, now());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'projects'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN projects text[] NOT NULL DEFAULT '{}'::text[];
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'licenses'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN licenses jsonb NOT NULL DEFAULT '[]'::jsonb;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'is_approved'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN is_approved boolean NOT NULL DEFAULT false;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'access_level'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN access_level text NOT NULL DEFAULT 'user';
  END IF;
END $$;

UPDATE public.profiles SET updated_at = timezone('utc'::text, now()) WHERE updated_at IS NULL;
ALTER TABLE public.profiles ALTER COLUMN updated_at SET NOT NULL;

-- 4. Dedicated Private Calendar Bearer Token Table (Fixes S2)
CREATE TABLE IF NOT EXISTS public.user_calendar_tokens (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_calendar_tokens_hash ON public.user_calendar_tokens(token_hash);

-- Migrate plaintext calendar tokens from profiles (if column exists)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'calendar_token'
  ) THEN
    INSERT INTO public.user_calendar_tokens (user_id, token_hash, created_at)
    SELECT 
      id AS user_id, 
      encode(digest(calendar_token, 'sha256'), 'hex') AS token_hash,
      timezone('utc'::text, now())
    FROM public.profiles
    WHERE calendar_token IS NOT NULL AND calendar_token <> ''
    ON CONFLICT (user_id) DO NOTHING;

    DROP INDEX IF EXISTS idx_profiles_calendar_token;
    ALTER TABLE public.profiles DROP COLUMN IF EXISTS calendar_token;
  END IF;
END $$;

-- 5. Cancellation Events Outbox Table (Fixes R4)
CREATE TABLE IF NOT EXISTS public.cancellation_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id bigint,
  tool_id bigint NOT NULL REFERENCES public.tools(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  cancelled_by uuid NOT NULL,
  tool_name text NOT NULL,
  date text NOT NULL,
  time text NOT NULL,
  end_time text NOT NULL,
  notified boolean NOT NULL DEFAULT false,
  notified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_cancellation_events_tool ON public.cancellation_events(tool_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cancellation_events_notified ON public.cancellation_events(notified) WHERE notified = false;

-- Email Logs for Quota & Rate Limiting (Fixes R4)
CREATE TABLE IF NOT EXISTS public.email_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recipient_email text NOT NULL,
  booking_id bigint,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_email_logs_sender ON public.email_logs(sender_id, created_at DESC);
ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_logs FORCE ROW LEVEL SECURITY;

-- 6. Upgrade public.bookings columns and backfill ranges (Fixes R2, R13)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'end_time'
  ) THEN
    ALTER TABLE public.bookings ADD COLUMN end_time time;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'starts_at'
  ) THEN
    ALTER TABLE public.bookings ADD COLUMN starts_at timestamptz;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'ends_at'
  ) THEN
    ALTER TABLE public.bookings ADD COLUMN ends_at timestamptz;
  END IF;
END $$;

-- Backfill legacy bookings missing end_time or range timestamps
-- Handles midnight rollover cleanly (e.g. 23:30 + 30m rolls into 00:00 of the next calendar day)
UPDATE public.bookings
SET
  starts_at = (date::text || ' ' || time::text)::timestamp AT TIME ZONE 'Europe/Vilnius',
  ends_at = (date::text || ' ' || time::text)::timestamp AT TIME ZONE 'Europe/Vilnius' + 
    CASE 
      WHEN end_time IS NOT NULL AND end_time > time THEN (end_time - time)
      ELSE interval '30 minutes'
    END
WHERE starts_at IS NULL OR ends_at IS NULL;

-- Synchronize end_time to match ends_at
UPDATE public.bookings
SET end_time = (ends_at AT TIME ZONE 'Europe/Vilnius')::time
WHERE end_time IS NULL;

-- Enforce NOT NULL on range columns
ALTER TABLE public.bookings ALTER COLUMN end_time SET NOT NULL;
ALTER TABLE public.bookings ALTER COLUMN starts_at SET NOT NULL;
ALTER TABLE public.bookings ALTER COLUMN ends_at SET NOT NULL;

-- Add check constraint for range order
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS booking_time_order;
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS booking_starts_ends_order;
ALTER TABLE public.bookings ADD CONSTRAINT booking_starts_ends_order CHECK (ends_at > starts_at);

-- Exclusion constraint for double booking prevention (S5)
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS no_double_booking;
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS no_overlapping_active_bookings;
ALTER TABLE public.bookings ADD CONSTRAINT no_overlapping_active_bookings EXCLUDE USING gist (
  tool_id WITH =,
  tstzrange(starts_at, ends_at, '[)') WITH &&
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_bookings_tool_date ON public.bookings(tool_id, date);
CREATE INDEX IF NOT EXISTS idx_bookings_user_date ON public.bookings(user_id, date);
CREATE INDEX IF NOT EXISTS idx_bookings_starts_at ON public.bookings(starts_at);
CREATE INDEX IF NOT EXISTS idx_bookings_ends_at ON public.bookings(ends_at);
CREATE INDEX IF NOT EXISTS idx_profiles_approved ON public.profiles(is_approved);
CREATE INDEX IF NOT EXISTS idx_profiles_access ON public.profiles(access_level);

-- 7. Helper Functions (Non-recursive)
CREATE OR REPLACE FUNCTION public.is_admin(p_user_id uuid)
RETURNS boolean AS $$
BEGIN
  IF p_user_id IS NULL THEN
    RETURN false;
  END IF;
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = p_user_id AND access_level = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.is_approved_user(p_user_id uuid)
RETURNS boolean AS $$
BEGIN
  IF p_user_id IS NULL THEN
    RETURN false;
  END IF;
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = p_user_id AND is_approved = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.is_approved_user(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.is_approved_user(uuid) TO authenticated;

-- 8. Safe Profile Update Validation Trigger (Fixes R3)
-- Allows updates when auth.uid() IS NULL (direct SQL editor admin provisioning) or caller is admin
CREATE OR REPLACE FUNCTION public.enforce_profile_update_rules()
RETURNS trigger AS $$
BEGIN
  IF auth.uid() IS NULL OR public.is_admin(auth.uid()) THEN
    NEW.updated_at := timezone('utc'::text, now());
    RETURN NEW;
  END IF;

  -- Non-admin self-service edit rules
  IF NEW.access_level IS DISTINCT FROM OLD.access_level THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify access_level' USING ERRCODE = '42501';
  END IF;
  IF NEW.is_approved IS DISTINCT FROM OLD.is_approved THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify is_approved' USING ERRCODE = '42501';
  END IF;
  IF NEW.licenses IS DISTINCT FROM OLD.licenses THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify licenses' USING ERRCODE = '42501';
  END IF;
  IF NEW.projects IS DISTINCT FROM OLD.projects THEN
    RAISE EXCEPTION 'Unauthorized: cannot modify projects' USING ERRCODE = '42501';
  END IF;

  NEW.updated_at := timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS tr_enforce_profile_update_rules ON public.profiles;
CREATE TRIGGER tr_enforce_profile_update_rules
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_profile_update_rules();

-- 9. Booking Business Rules Triggers (Fixes R7)
CREATE OR REPLACE FUNCTION public.enforce_booking_rules()
RETURNS trigger AS $$
DECLARE
  v_caller_id uuid;
  v_is_admin boolean;
  v_tool record;
  v_profile record;
BEGIN
  v_caller_id := auth.uid();
  IF v_caller_id IS NULL THEN
    -- System jobs / migrations / direct database admin
    RETURN NEW;
  END IF;

  v_is_admin := public.is_admin(v_caller_id);
  IF v_is_admin THEN
    RETURN NEW;
  END IF;

  -- Non-admin rules:
  -- 1. Owner check
  IF NEW.user_id <> v_caller_id THEN
    RAISE EXCEPTION 'Unauthorized: user_id must match authenticated user' USING ERRCODE = '42501';
  END IF;

  -- 2. Fetch tool
  SELECT * INTO v_tool FROM public.tools WHERE id = NEW.tool_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tool not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_tool.status <> 'up' THEN
    RAISE EXCEPTION 'Tool is not available' USING ERRCODE = '22023';
  END IF;

  -- 3. Fetch profile
  SELECT * INTO v_profile FROM public.profiles WHERE id = v_caller_id;
  IF NOT FOUND OR NOT v_profile.is_approved THEN
    RAISE EXCEPTION 'User profile not found or not approved' USING ERRCODE = '42501';
  END IF;

  -- 4. License check
  IF v_tool.license_req THEN
    IF NOT (v_profile.licenses ? NEW.tool_id::text) THEN
      RAISE EXCEPTION 'User lacks required license for this tool' USING ERRCODE = '42501';
    END IF;
  END IF;

  -- 5. Project check
  IF array_length(v_profile.projects, 1) > 0 AND NOT (NEW.project = ANY(v_profile.projects)) THEN
    RAISE EXCEPTION 'User is not assigned to project %', NEW.project USING ERRCODE = '42501';
  END IF;

  -- 6. Time and history checks
  IF TG_OP = 'INSERT' THEN
    IF NEW.starts_at < (now() - interval '5 minutes') THEN
      RAISE EXCEPTION 'Cannot create bookings in the past' USING ERRCODE = '22023';
    END IF;
  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD.ends_at < now() THEN
      RAISE EXCEPTION 'Cannot modify past bookings' USING ERRCODE = '42501';
    END IF;
    IF OLD.starts_at <= now() AND OLD.ends_at > now() THEN
      -- In-progress: cannot move start time
      IF NEW.starts_at <> OLD.starts_at THEN
        RAISE EXCEPTION 'Cannot alter start time of an in-progress booking' USING ERRCODE = '42501';
      END IF;
      IF NEW.ends_at < now() THEN
        RAISE EXCEPTION 'Cannot end an in-progress booking in the past' USING ERRCODE = '22023';
      END IF;
    ELSE
      -- Future booking: cannot move start into past
      IF NEW.starts_at < (now() - interval '5 minutes') THEN
        RAISE EXCEPTION 'Cannot move booking start into the past' USING ERRCODE = '22023';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS tr_enforce_booking_rules ON public.bookings;
CREATE TRIGGER tr_enforce_booking_rules
  BEFORE INSERT OR UPDATE ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_booking_rules();

-- Deletion trigger (Fixes R7)
CREATE OR REPLACE FUNCTION public.enforce_booking_delete_rules()
RETURNS trigger AS $$
DECLARE
  v_caller_id uuid;
BEGIN
  v_caller_id := auth.uid();
  IF v_caller_id IS NULL OR public.is_admin(v_caller_id) THEN
    RETURN OLD;
  END IF;

  IF OLD.user_id <> v_caller_id THEN
    RAISE EXCEPTION 'Unauthorized: cannot delete another user booking' USING ERRCODE = '42501';
  END IF;

  IF OLD.ends_at < now() THEN
    RAISE EXCEPTION 'Cannot delete past bookings' USING ERRCODE = '42501';
  END IF;

  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS tr_enforce_booking_delete_rules ON public.bookings;
CREATE TRIGGER tr_enforce_booking_delete_rules
  BEFORE DELETE ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_booking_delete_rules();

-- 10. Atomic Multi-Slot Booking Update RPC (Fixes R1, R7)
CREATE OR REPLACE FUNCTION public.update_booking_group(
  p_old_ids bigint[],
  p_tool_id bigint,
  p_date date,
  p_time time,
  p_end_time time,
  p_project text,
  p_user_name text,
  p_tool_name text
)
RETURNS jsonb AS $$
DECLARE
  v_caller_id uuid;
  v_is_admin boolean;
  v_user_profile record;
  v_tool record;
  v_found_count integer;
  v_distinct_users integer;
  v_distinct_tools integer;
  v_group_owner uuid;
  v_starts_at timestamptz;
  v_ends_at timestamptz;
  v_new_booking record;
BEGIN
  v_caller_id := auth.uid();
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;

  IF p_old_ids IS NULL OR array_length(p_old_ids, 1) IS NULL OR array_length(p_old_ids, 1) = 0 THEN
    RAISE EXCEPTION 'Empty or invalid booking IDs array' USING ERRCODE = '22023';
  END IF;

  -- Reject duplicate IDs in input array
  IF (SELECT count(DISTINCT id) FROM unnest(p_old_ids) AS id) <> array_length(p_old_ids, 1) THEN
    RAISE EXCEPTION 'Duplicate booking IDs supplied' USING ERRCODE = '22023';
  END IF;

  v_is_admin := public.is_admin(v_caller_id);

  -- Lock all target rows FOR UPDATE
  PERFORM 1 FROM public.bookings WHERE id = ANY(p_old_ids) FOR UPDATE;

  -- Verify ownership and consistency across all rows
  SELECT 
    count(*),
    count(DISTINCT user_id),
    count(DISTINCT tool_id),
    min(user_id::text)::uuid
  INTO 
    v_found_count,
    v_distinct_users,
    v_distinct_tools,
    v_group_owner
  FROM public.bookings
  WHERE id = ANY(p_old_ids);

  -- 1. All IDs must exist
  IF v_found_count <> array_length(p_old_ids, 1) THEN
    RAISE EXCEPTION 'One or more booking IDs not found' USING ERRCODE = 'P0002';
  END IF;

  -- 2. All target bookings must belong to the exact same user
  IF v_distinct_users <> 1 THEN
    RAISE EXCEPTION 'Cannot update bookings across multiple users' USING ERRCODE = '42501';
  END IF;

  -- 3. Caller must own all bookings or be an admin
  IF v_group_owner <> v_caller_id AND NOT v_is_admin THEN
    RAISE EXCEPTION 'Unauthorized: you do not own all specified bookings' USING ERRCODE = '42501';
  END IF;

  -- 4. All target bookings must belong to the same tool
  IF v_distinct_tools <> 1 THEN
    RAISE EXCEPTION 'Cannot update bookings across multiple tools' USING ERRCODE = '22023';
  END IF;

  -- 5. If not admin, verify none of the target bookings are in the past
  IF NOT v_is_admin THEN
    IF EXISTS (
      SELECT 1 FROM public.bookings
      WHERE id = ANY(p_old_ids) AND ends_at < now()
    ) THEN
      RAISE EXCEPTION 'Cannot modify past bookings' USING ERRCODE = '42501';
    END IF;
  END IF;

  -- Validate target tool
  SELECT * INTO v_tool FROM public.tools WHERE id = p_tool_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tool not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_tool.status <> 'up' AND NOT v_is_admin THEN
    RAISE EXCEPTION 'Tool is not available for booking' USING ERRCODE = '22023';
  END IF;

  -- Validate user profile, license, and project
  SELECT * INTO v_user_profile FROM public.profiles WHERE id = v_group_owner;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User profile not found' USING ERRCODE = 'P0002';
  END IF;
  IF NOT v_user_profile.is_approved AND NOT v_is_admin THEN
    RAISE EXCEPTION 'User is not approved' USING ERRCODE = '42501';
  END IF;

  IF v_tool.license_req AND NOT v_is_admin THEN
    IF NOT (v_user_profile.licenses ? p_tool_id::text) THEN
      RAISE EXCEPTION 'User lacks required license for this tool' USING ERRCODE = '42501';
    END IF;
  END IF;

  -- Validate assigned project for non-admin
  IF NOT v_is_admin THEN
    IF array_length(v_user_profile.projects, 1) > 0 AND NOT (p_project = ANY(v_user_profile.projects)) THEN
      RAISE EXCEPTION 'User is not assigned to project %', p_project USING ERRCODE = '42501';
    END IF;
  END IF;

  -- Calculate timestamps in Europe/Vilnius
  v_starts_at := (p_date::text || ' ' || p_time::text)::timestamp AT TIME ZONE 'Europe/Vilnius';
  v_ends_at := (p_date::text || ' ' || p_time::text)::timestamp AT TIME ZONE 'Europe/Vilnius' + 
    CASE 
      WHEN p_end_time > p_time THEN (p_end_time - p_time)
      ELSE (interval '24 hours' - (p_time - p_end_time))
    END;

  IF v_ends_at <= v_starts_at THEN
    RAISE EXCEPTION 'End time must be after start time' USING ERRCODE = '22023';
  END IF;

  IF NOT v_is_admin AND v_starts_at < (now() - interval '5 minutes') THEN
    RAISE EXCEPTION 'Cannot create bookings in the past' USING ERRCODE = '22023';
  END IF;

  -- Atomically delete all old slots
  DELETE FROM public.bookings WHERE id = ANY(p_old_ids);

  -- Insert the unified replacement booking
  INSERT INTO public.bookings (
    tool_id, tool_name, user_id, user_name, project,
    date, time, end_time, starts_at, ends_at, created_at
  ) VALUES (
    p_tool_id, p_tool_name, v_group_owner, p_user_name, p_project,
    p_date, p_time, p_end_time, v_starts_at, v_ends_at, timezone('utc'::text, now())
  )
  RETURNING * INTO v_new_booking;

  RETURN to_jsonb(v_new_booking);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.update_booking_group(bigint[], bigint, date, time, time, text, text, text) FROM public;
GRANT EXECUTE ON FUNCTION public.update_booking_group(bigint[], bigint, date, time, time, text, text, text) TO authenticated;

-- 11. Cancellation RPC (Fixes R4, R9)
CREATE OR REPLACE FUNCTION public.cancel_booking(
  p_booking_id bigint,
  p_notify_users boolean DEFAULT false
)
RETURNS jsonb AS $$
DECLARE
  v_caller_id uuid;
  v_is_admin boolean;
  v_booking record;
  v_event_id uuid := NULL;
BEGIN
  v_caller_id := auth.uid();
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;

  v_is_admin := public.is_admin(v_caller_id);

  SELECT * INTO v_booking
  FROM public.bookings
  WHERE id = p_booking_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_booking.user_id <> v_caller_id AND NOT v_is_admin THEN
    RAISE EXCEPTION 'Unauthorized: cannot cancel another user booking' USING ERRCODE = '42501';
  END IF;

  IF v_booking.ends_at < now() AND NOT v_is_admin THEN
    RAISE EXCEPTION 'Cannot cancel past bookings' USING ERRCODE = '42501';
  END IF;

  IF p_notify_users THEN
    INSERT INTO public.cancellation_events (
      booking_id, tool_id, user_id, cancelled_by,
      tool_name, date, time, end_time, created_at
    ) VALUES (
      v_booking.id, v_booking.tool_id, v_booking.user_id, v_caller_id,
      v_booking.tool_name, v_booking.date::text, v_booking.time::text, v_booking.end_time::text,
      timezone('utc'::text, now())
    )
    RETURNING id INTO v_event_id;
  END IF;

  DELETE FROM public.bookings WHERE id = p_booking_id;

  RETURN jsonb_build_object(
    'cancelled_id', p_booking_id,
    'cancellation_event_id', v_event_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.cancel_booking(bigint, boolean) FROM public;
GRANT EXECUTE ON FUNCTION public.cancel_booking(bigint, boolean) TO authenticated;

-- 12. Calendar Token Management RPCs (Fixes S2)
CREATE OR REPLACE FUNCTION public.rotate_calendar_token(p_token_hash text)
RETURNS boolean AS $$
DECLARE
  v_user_id uuid;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;

  IF p_token_hash IS NULL OR length(p_token_hash) <> 64 THEN
    RAISE EXCEPTION 'Invalid token hash format: must be 64-char hex SHA-256' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.user_calendar_tokens (user_id, token_hash, created_at)
  VALUES (v_user_id, p_token_hash, timezone('utc'::text, now()))
  ON CONFLICT (user_id) 
  DO UPDATE SET 
    token_hash = EXCLUDED.token_hash,
    created_at = EXCLUDED.created_at;

  RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.rotate_calendar_token(text) FROM public;
GRANT EXECUTE ON FUNCTION public.rotate_calendar_token(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.has_calendar_token()
RETURNS boolean AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN false;
  END IF;

  RETURN EXISTS (
    SELECT 1 FROM public.user_calendar_tokens
    WHERE user_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.has_calendar_token() FROM public;
GRANT EXECUTE ON FUNCTION public.has_calendar_token() TO authenticated;

-- 13. Row-Level Security (RLS) Policies (Fixes S3, R8)
ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tools_read_all" ON public.tools;
DROP POLICY IF EXISTS "tools_admin_all" ON public.tools;
CREATE POLICY "tools_read_all" ON public.tools
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "tools_admin_all" ON public.tools
  FOR ALL TO authenticated USING (public.is_admin(auth.uid()));

-- PROFILES (Fixes R8)
-- Direct SQL Editor / service role / migrations (auth.uid() IS NULL) have full access.
-- Pending users can only see their own profile.
-- Approved users and admins can see directory profiles.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
DROP POLICY IF EXISTS "profiles_select_policy" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_self_or_admin" ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_all" ON public.profiles;

CREATE POLICY "profiles_select_policy" ON public.profiles
  FOR SELECT
  USING (
    auth.uid() IS NULL
    OR (auth.uid() = id) 
    OR public.is_approved_user(auth.uid()) 
    OR public.is_admin(auth.uid())
  );

CREATE POLICY "profiles_update_self_or_admin" ON public.profiles
  FOR UPDATE
  USING (auth.uid() IS NULL OR auth.uid() = id OR public.is_admin(auth.uid()))
  WITH CHECK (auth.uid() IS NULL OR auth.uid() = id OR public.is_admin(auth.uid()));

CREATE POLICY "profiles_admin_all" ON public.profiles
  FOR ALL
  USING (auth.uid() IS NULL OR public.is_admin(auth.uid()));

-- BOOKINGS (Fixes R8)
-- Direct SQL Editor / migrations have full access.
-- Unapproved accounts cannot view any bookings.
-- Approved users and admins can view bookings.
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bookings_select_authenticated" ON public.bookings;
DROP POLICY IF EXISTS "bookings_select_policy" ON public.bookings;
DROP POLICY IF EXISTS "bookings_insert_own" ON public.bookings;
DROP POLICY IF EXISTS "bookings_update_own_or_admin" ON public.bookings;
DROP POLICY IF EXISTS "bookings_delete_own_or_admin" ON public.bookings;

CREATE POLICY "bookings_select_policy" ON public.bookings
  FOR SELECT
  USING (
    auth.uid() IS NULL
    OR public.is_approved_user(auth.uid()) 
    OR public.is_admin(auth.uid())
  );

CREATE POLICY "bookings_insert_own" ON public.bookings
  FOR INSERT
  WITH CHECK (
    auth.uid() IS NULL
    OR (public.is_approved_user(auth.uid()) AND auth.uid() = user_id)
    OR public.is_admin(auth.uid())
  );

CREATE POLICY "bookings_update_own_or_admin" ON public.bookings
  FOR UPDATE
  USING (auth.uid() IS NULL OR auth.uid() = user_id OR public.is_admin(auth.uid()))
  WITH CHECK (auth.uid() IS NULL OR auth.uid() = user_id OR public.is_admin(auth.uid()));

CREATE POLICY "bookings_delete_own_or_admin" ON public.bookings
  FOR DELETE
  USING (auth.uid() IS NULL OR auth.uid() = user_id OR public.is_admin(auth.uid()));

-- USER CALENDAR TOKENS
ALTER TABLE public.user_calendar_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_calendar_tokens FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_calendar_tokens_owner" ON public.user_calendar_tokens;
CREATE POLICY "user_calendar_tokens_owner" ON public.user_calendar_tokens
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- CANCELLATION EVENTS
ALTER TABLE public.cancellation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cancellation_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cancellation_events_select" ON public.cancellation_events;
CREATE POLICY "cancellation_events_select" ON public.cancellation_events
  FOR SELECT TO authenticated
  USING (auth.uid() = cancelled_by OR public.is_admin(auth.uid()));
